"""
Django settings for vidsocial project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
# settings.py
AUTH_USER_MODEL = 'vid_user.UserProfile'

from pathlib import Path


import os

from decouple import config


# Example usage
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y064s%@s22m(=@ijblec0di88g&=!0=xh)682!5^-3_!2v=4&o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True




# Application definition

INSTALLED_APPS = [
    "channels",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vid_user',
    "rest_framework",
    "vid_sponser",
    "vid_customer",
    "django_extensions",
    # "vid_app_dr",
    "vid_worker",
    "sslserver",
    
]

GRAPH_MODELS ={
'all_applications': True,
'graph_models': True,
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "corsheaders.middleware.CorsMiddleware",
    # 'channels.middleware.AuthMiddlewareStack',
]

ROOT_URLCONF = 'vidsocial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Check this directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'vidsocial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




DATABASES = {
    'default': {
        'ENGINE': config('SQL_ENGINE'),
        'NAME': config('SQL_DB_NAME'),
        'USER': config('SQL_USER'),
        'PASSWORD': config('SQL_PASSWORD'),
        'HOST': config('SQL_HOST'),  # Change this to your MSSQL server address if not running locally.
        'PORT': config('SQL_PORT'),       # Change this to your MSSQL server port if different.
       }
}




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'mail.vidsocial.net'  
EMAIL_PORT = 465  
EMAIL_HOST_USER = 'contact@vidsocial.net'
EMAIL_HOST_PASSWORD = 'VidSocial@12345' 
EMAIL_USE_SSL = True  
DEFAULT_FROM_EMAIL = "contact@vidsocial.net"


SWAGGER_YAML_FILE =(f'{BASE_DIR}/vid_user/static/vidapp.yaml')  

LANGUAGE =(f'{BASE_DIR}/translations.json')  

CORS_ALLOW_HEADERS = [
"accept",
"accept-encoding",
"authorization",
"content-type",
"dnt",
"origin",
"user-agent",
"x-csrftoken",
"x-requested-with",
"uploader-chunk-number",
"uploader-chunks-total",
"uploader-file-id"

]
ALLOWED_HOSTS = ['*']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "videos" 

CORS_ALLOW_ALL_ORIGINS = True 
# Allow specific origins
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',  # For development
#     # Add other allowed origins here
# ]

CORS_ALLOWED_ORIGINS = [
    '*',  # Allow all origins
]

# Specify allowed methods and headers
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    # Add other allowed headers here
]



REDIS_SERVER_URL=config('REDIS_SERVER_URL')
CELERY_BROKER_URL =config('REDIS_SERVER_URL')
"amqp://myuser:mypassword@localhost:5672/myvhost"
result_backend=config('REDIS_SERVER_URL')

accept_content = ['application/json']
result_serializer  = 'json'
task_serializer  = 'json'
timezone  ='Asia/Calcutta'

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_ENABLE_UTC = True
DJANGO_CELERY_BEAT_TZ_AWARE = False
broker_connection_retry = True
broker_connection_max_retries = 0
broker_connection_timeout = 120
broker_heartbeat = 10 
broker_heartbeat_checkrate = 2.0
broker_connection_retry_on_startup=True



#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
#MEDIA_URL = '/media/'
# settings.py

ASGI_APPLICATION = 'vidsocial.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}
