# Generated by Django 4.2.7 on 2023-11-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0004_alter_userprofile_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcoinclaim',
            name='payment_request_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vid_user.paymentrequest'),
        ),
        migrations.AlterField(
            model_name='requestcoinclaim',
            name='request_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('cancel', 'Cancel')], default='draft', max_length=10),
        ),
    ]
