# Generated by Django 4.2.7 on 2023-11-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0005_alter_requestcoinclaim_payment_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='request_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('cancel', 'Cancel')], default='draft', max_length=10),
        ),
    ]
