# Generated by Django 4.2.7 on 2023-11-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0006_remove_paymentrequest_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='sponser_bank_acc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vid_user.bankaccount'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='sponser_binance_acc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vid_user.binanceaccount'),
        ),
    ]
