# Generated by Django 4.2.7 on 2023-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0008_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_permission',
            field=models.BooleanField(default=True),
        ),
    ]
