# Generated by Django 4.2.7 on 2023-12-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0009_userprofile_login_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcoinclaim',
            name='notify_payment_sent',
            field=models.BooleanField(default=False),
        ),
    ]
