# Generated by Django 4.2.7 on 2023-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0010_requestcoinclaim_notify_payment_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
