# Generated by Django 4.2.7 on 2023-12-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0011_review_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dial_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
