# Generated by Django 4.2.7 on 2023-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0012_country_dial_code_country_flag_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
