# Generated by Django 4.2.7 on 2023-12-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0013_alter_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentQA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=0)),
            ],
        ),
    ]
