# Generated by Django 4.2.7 on 2023-12-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0014_frequentqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentqa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
