# Generated by Django 4.2.7 on 2023-12-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0015_frequentqa_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signup_step',
            field=models.IntegerField(default=0),
        ),
    ]
