# Generated by Django 4.2.7 on 2023-12-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0017_coinmanagement_bar_code_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_active',
        ),
    ]
