# Generated by Django 4.2.7 on 2023-12-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0018_remove_favorite_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
