# Generated by Django 4.2.7 on 2023-12-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0022_buycredit_bar_code_image_buycredit_check_out_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycredit',
            name='bar_code_image',
        ),
        migrations.RemoveField(
            model_name='buycredit',
            name='check_out_url',
        ),
    ]
