# Generated by Django 4.2.7 on 2023-12-13 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0024_coinmanagement_bar_code_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HelpAndSupport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=500)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_checked_by_admin', models.BooleanField(default=False)),
                ('reply_message_by_admin', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_help_and_support', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
