# Generated by Django 4.2.7 on 2023-12-13 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0025_report_user_id_helpandsupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sponser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponser_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
