# Generated by Django 4.2.7 on 2023-12-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0026_alter_report_sponser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpandsupport',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
