# Generated by Django 4.2.7 on 2023-12-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0029_paymentrequest_bar_code_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='bar_code_image',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='check_out_url',
        ),
    ]
