# Generated by Django 4.2.7 on 2023-12-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0030_remove_paymentrequest_bar_code_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycredit',
            name='bar_code_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buycredit',
            name='check_out_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
