# Generated by Django 4.2.7 on 2023-12-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0031_buycredit_bar_code_image_buycredit_check_out_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycredit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('timeout', 'Timeout'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
