# Generated by Django 4.2.7 on 2023-12-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0032_buycredit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_approval_state',
            field=models.CharField(choices=[('none', 'None'), ('decline', 'Decline'), ('approve', 'Approve')], default='none', max_length=10),
        ),
    ]
