# Generated by Django 4.2.7 on 2023-12-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0033_alter_userprofile_account_approval_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
