# Generated by Django 4.2.7 on 2023-12-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0034_userprofile_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='device_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
