# Generated by Django 4.2.7 on 2023-12-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0036_alter_giftgallery_gift_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcoinclaim',
            name='accepted_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
