# Generated by Django 4.2.7 on 2023-12-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0037_requestcoinclaim_accepted_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcoinclaim',
            name='request_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('cancel', 'Cancel'), ('inprocess', 'Inprocess')], default='draft', max_length=10),
        ),
    ]
