# Generated by Django 4.2.7 on 2023-12-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0038_alter_requestcoinclaim_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reason_of_declination_identity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
