# Generated by Django 4.2.7 on 2023-12-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0039_userprofile_reason_of_declination_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
