# Generated by Django 4.2.7 on 2023-12-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0041_remove_warning_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
