# Generated by Django 4.2.7 on 2023-12-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0044_warning_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='block_call',
            field=models.IntegerField(default=0),
        ),
    ]
