# Generated by Django 4.2.7 on 2023-12-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0045_userprofile_block_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='previous_warning',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
