# Generated by Django 4.2.7 on 2023-12-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0046_warning_previous_warning'),
    ]

    operations = [
        migrations.CreateModel(
            name='prohibitedbank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prohibitedbankcode', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vid_user.country')),
            ],
        ),
    ]
