# Generated by Django 4.2.7 on 2023-12-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0047_prohibitedbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='block_call',
        ),
    ]
