# Generated by Django 4.2.7 on 2023-12-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0048_remove_userprofile_block_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='block_call_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
