# Generated by Django 4.2.7 on 2024-01-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0049_userprofile_block_call_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEssentials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
