# Generated by Django 4.2.7 on 2024-01-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0050_adminessentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminessentials',
            name='is_active',
        ),
    ]
