# Generated by Django 4.2.7 on 2024-01-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0051_remove_adminessentials_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminessentials',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
