# Generated by Django 4.2.7 on 2024-01-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0052_adminessentials_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='prohibitedbank',
            name='prohibited_bank_exist',
            field=models.BooleanField(default=False),
        ),
    ]
