# Generated by Django 4.2.7 on 2024-01-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0055_country_prohibited_bank_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='User_warning_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
