# Generated by Django 4.2.7 on 2024-01-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0056_warning_user_warning_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warning',
            name='User_warning_action',
        ),
    ]
