# Generated by Django 4.2.7 on 2024-01-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0057_remove_warning_user_warning_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='user_warning_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
