# Generated by Django 4.2.7 on 2024-01-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0058_warning_user_warning_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcoinclaim',
            name='accepted_by_admin',
        ),
    ]
