# Generated by Django 4.2.7 on 2024-01-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0059_remove_requestcoinclaim_accepted_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcoinclaim',
            name='payment_done_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
