# Generated by Django 4.2.7 on 2024-01-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0060_requestcoinclaim_payment_done_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcoinclaim',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
