# Generated by Django 4.2.7 on 2024-01-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0062_alter_callsession_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmanagement',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
