# Generated by Django 4.2.7 on 2024-01-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0063_coinmanagement_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='call_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='duration',
            field=models.TimeField(),
        ),
    ]
