# Generated by Django 4.2.7 on 2024-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0064_callsession_call_count_alter_callsession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
