# Generated by Django 4.2.7 on 2024-01-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0065_alter_callsession_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsession',
            name='duration',
        ),
    ]
