# Generated by Django 4.2.7 on 2024-01-19 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0066_remove_callsession_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
