# Generated by Django 4.2.7 on 2024-01-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0067_callsession_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftmanagement',
            name='gifts_processed',
            field=models.BooleanField(default=False),
        ),
    ]
