# Generated by Django 4.2.7 on 2024-02-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0070_calldeductioncoin_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcoinclaim',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
