# Generated by Django 4.2.7 on 2024-02-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0072_paymentrequest_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_url_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
