# Generated by Django 4.2.7 on 2024-02-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0073_userprofile_image_url_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
