# Generated by Django 4.2.7 on 2024-02-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0074_fileurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
