# Generated by Django 4.2.7 on 2024-02-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0075_userprofile_online_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='warning_clear',
            field=models.BooleanField(default=False),
        ),
    ]
