# Generated by Django 4.2.7 on 2024-02-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0076_warning_warning_clear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warning',
            name='warning_clear',
        ),
    ]
