# Generated by Django 4.2.7 on 2024-02-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0077_remove_warning_warning_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_clear',
            field=models.BooleanField(default=False),
        ),
    ]
