# Generated by Django 4.2.7 on 2024-02-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0078_report_report_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='user_call_count',
            field=models.IntegerField(default=0),
        ),
    ]
