# Generated by Django 4.2.7 on 2024-02-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0080_buycredit_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycredit',
            name='payment_add',
            field=models.BooleanField(default=False),
        ),
    ]
