# Generated by Django 4.2.7 on 2024-02-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0081_buycredit_payment_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='CallEnd',
            field=models.BooleanField(default=False),
        ),
    ]
