# Generated by Django 4.2.7 on 2024-03-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0082_callsession_callend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
