# Generated by Django 4.2.7 on 2024-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0083_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='En', max_length=150, null=True, unique=True),
        ),
    ]
