# Generated by Django 4.2.7 on 2024-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0087_alter_prohibitedbank_prohibitedbankcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopWorker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
