# Generated by Django 4.2.7 on 2024-03-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vid_user', '0088_topworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='report_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vid_user.report'),
        ),
    ]
