# Generated by Django 4.2.7 on 2024-01-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_worker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
