# Generated by Django 4.2.7 on 2024-01-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_worker', '0002_remove_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
