# Generated by Django 4.2.7 on 2024-01-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_worker', '0003_video_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user_id',
        ),
    ]
