# Generated by Django 4.2.7 on 2024-01-16 10:17

from django.db import migrations, models
import vid_worker.models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_worker', '0005_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=vid_worker.models.user_directory_path),
        ),
    ]
